# Generated by Django 4.1 on 2022-11-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donuts',
            new_name='Donut',
        ),
    ]
